CRM Tele2 ASP/Models/Call.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRM_Tele2_ASP.Models
{
    public class Call()
    {
        public int Id { get; set; }

        public string ClientPhoneNumber { get; set; } = null!; 
        public string? ClientName { get; set; }
        public string? ClientAddress { get; set; }

        public string? Comment { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime DateOfCall { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfScheduledCall { get; set; }

        [ForeignKey(nameof(ClientPhoneNumber))]
        public Client? Client { get; set; }
    }
}

CRM Tele2 ASP/Models/Client.cs
using System.ComponentModel.DataAnnotations;

namespace CRM_Tele2_ASP.Models
{
    public class Client
    {
        
        public int Id { get; set; }
        [Key]
        [Required(ErrorMessage ="Номер телефона - обязательное поле")]
        [StringLength(12), MinLength(11, ErrorMessage = "Номер телефона должен быть не короче 11 символов")]
        [Phone]
        [RegularExpression(@"^\+77\d{9}",ErrorMessage ="Введите телефон в формате +77...")]
        public string PhoneNumber { get; set; } = "Все семёрки";

        [StringLength(100, ErrorMessage ="Слишком длинное имя")]
        public string? Name { get; set; } = "Безымянный";

        [StringLength(100, ErrorMessage = "Слишком длинный адрес")]
        public string? Address { get; set; } = "Без определённого места жительства";
    }
}

CRM Tele2 ASP/Models/ClientCallViewModel.cs
namespace CRM_Tele2_ASP.Models
{
    public class ClientCallViewModel
    {
        public Client Client { get; set; } = new Client();
        public Call Call { get; set; } = new Call();
    }
}

CRM Tele2 ASP/Models/ErrorViewModel.cs
namespace CRM_Tele2_ASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRM Tele2 ASP/Controllers/AddNumberController.cs
using CRM_Tele2_ASP.Models;
using CRM_Tele2_ASP.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CRM_Tele2_ASP.Controllers
{
    public class AddNumberController : Controller
    {
        private readonly DataBaseContext db;
        public AddNumberController(DataBaseContext context)
        {
            db = context;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateClientAndCall(ClientCallViewModel model)
        {
            if (model.Call.DateOfScheduledCall == null)
            {
                ModelState.AddModelError("Call.DateOfScheduledCall", "Укажите дату следующего звонка");               
            }
            ModelState.Remove("Call.ClientPhoneNumber");
            if (ModelState.IsValid)
            {
                db.Clients.Add(model.Client);
                await db.SaveChangesAsync();

                model.Call.ClientPhoneNumber = model.Client.PhoneNumber;
                model.Call.ClientName = model.Client.Name;
                model.Call.ClientAddress = model.Client.Address;
                model.Call.DateOfCall = DateTime.Now;
                db.Calls.Add(model.Call);

                await db.SaveChangesAsync();
                return Redirect("/");
            }

            return View("Index");
        }

    }
}

CRM Tele2 ASP/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRM_Tele2_ASP.Models;
using CRM_Tele2_ASP.Services;
using Microsoft.EntityFrameworkCore;

namespace CRM_Tele2_ASP.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    private readonly DataBaseContext db;
    public HomeController(ILogger<HomeController> logger, DataBaseContext context)
    {
        _logger = logger;
        db = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<JsonResult> GetScheduledCalls()
    {
        var allCalls = await db.Calls.ToListAsync();

        var latestCalls = allCalls
            .GroupBy(c => c.ClientPhoneNumber)
            .Select(g => g.OrderByDescending(c => c.DateOfCall).First())
            .Where(c => c.DateOfScheduledCall != null
                     && c.DateOfScheduledCall < DateTime.Today.AddDays(1))
            .OrderBy(c => c.DateOfScheduledCall);

        var result = latestCalls.Select(c => new
        {
            c.ClientName,
            c.ClientAddress,
            c.ClientPhoneNumber,
            c.Comment,
            DateOfCall = c.DateOfCall.ToString("dd.MM.yyyy HH:mm"),
            DateOfScheduledCall = c.DateOfScheduledCall?.ToString("dd.MM.yyyy HH:mm")
        });

        return Json(result);
    }



    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CRM Tele2 ASP/Controllers/OutGoingCallController.cs
using CRM_Tele2_ASP.Models;
using CRM_Tele2_ASP.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data.Common;
using System.Text.RegularExpressions;

namespace CRM_Tele2_ASP.Controllers
{
    public class OutGoingCallController : Controller
    {
        private readonly DataBaseContext db;
        
        public OutGoingCallController(DataBaseContext context)
        {
            db = context;
        }

        public ActionResult OutGoingCallIndex(string phone)
        {
            if (phone == null) return View();

            var clients = (List <Client>)SearchClientsByNumber(phone).Value!;
            Client client = clients[0];

            ClientCallViewModel cc = new()
            {
                Call = new Call(),
                Client = client
            };

            return View(cc);           
        }

        public async Task<IActionResult> CreateCall(Call call)
        {
            await CreateClientIfClientNotExist(call);

            await ValidateCallData(call);

            if (ModelState.IsValid)
            {
                call.DateOfCall = DateTime.Now;
                db.Calls.Add(call);

                await db.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return View("OutGoingCallIndex");
        }

        public async Task ValidateCallData(Call call)
        {
            if (call.ClientPhoneNumber == null || call.ClientPhoneNumber.Length < 12)
                ModelState.AddModelError("Call.ClientPhoneNumber", "Это поле является обязательным");

            if (!Regex.IsMatch(call.ClientPhoneNumber!, @"^\+77\d{9}"))
                ModelState.AddModelError("Call.ClientPhoneNumber", "Неверный формат номера. Введите телефон в формате +77...");
        }

        public async Task CreateClientIfClientNotExist(Call call)
        {
            bool isClientExist = db.Clients.Contains(new Client { PhoneNumber = call.ClientPhoneNumber });

            if (!isClientExist)
            {
                db.Add(new Client { Name = call.ClientName, Address = call.ClientAddress, PhoneNumber = call.ClientPhoneNumber });
                await db.SaveChangesAsync();
            }
        }

        public JsonResult SearchClientsByNumber(string numberPart)
        {
            var results = db.Clients.Where(c => c.PhoneNumber.Contains(numberPart))
                                    .ToList();
            return Json(results);
        }
        public JsonResult LoadCallHistory(string phoneNumber)
        {
            var results = db.Calls.Where(c => c.ClientPhoneNumber == phoneNumber)
                                  .Select(c => new
                                  {
                                      label = c.Comment,
                                      dateOfCall = c.DateOfCall,
                                      dateOfScheduledCall = c.DateOfScheduledCall
                                  })
                                  .ToList();
            var calls = results.Select(c => new
            {
                c.label,
                dateOfCall = c.dateOfCall.ToString("dd.MM.yyyy HH:mm"),
                dateOfScheduledCall = c.dateOfScheduledCall?.ToString("dd.MM.yyyy HH: mm")
            });
            return Json(calls);
        }
    }
}

CRM Tele2 ASP/Views/AddNumber/Index.cshtml
@model ClientCallViewModel

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="stylesheet" href="~/css/addNumber.css" asp-append-version="true" />
</head>

<body>
    <div class="container">
        <div class="stack-panel">
            <form asp-action="CreateClientAndCall" asp-controller="AddNumber">
                <input type="text" asp-for="Client.Name" placeholder="Введите имя" />
                <span asp-validation-for="Client.Name" class="text-danger"></span>

                <input type="text" asp-for="Client.PhoneNumber" asp-for="Call.ClientPhoneNumber" placeholder="Введите номер" value="+77"/>
                <span asp-validation-for="Client.PhoneNumber" class="text-danger"></span>

                <input type="text" asp-for="Client.Address" placeholder="Введите адрес"/>
                <span asp-validation-for="Client.Address" class="text-danger"></span>

                <textarea asp-for="Call.Comment" placeholder="Комментарий"></textarea>

                <label for="date-of-scheduled-call-input">Назначить звонок</label>
                <input id="date-of-scheduled-call-input" type="datetime-local" asp-for="Call.DateOfScheduledCall" />
                <span asp-validation-for="Call.DateOfScheduledCall" class="text-danger"></span>

                <button>Добавить</button>
            </form>
        </div>
    </div>
</body>

CRM Tele2 ASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="stylesheet" href="~/css/mainPage.css" asp-append-version="true" />
    <script src="~/js/addNumber.js"></script>
</head>

<body>
    <div class="container">
        <div class="sidebar">
            <button onclick="location.href='@Url.Action("Index", "AddNumber")'">Добавить</button>
            <button onclick="location.href='@Url.Action("OutGoingCallIndex", "OutGoingCall")'">Исходящий</button>
        </div>
        <div class="main-content">
            <h1>Назначенные</h1>
            <table id="scheduledCallsTable">
                <thead>
                    <tr>
                        <th>Имя</th>
                        <th>Адрес</th>
                        <th>Номер телефона</th>
                        <th>Комментарий</th>
                        <th>Дата последнего контакта</th>
                        <th>Отложено на</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
    </div>
    <script src="~/js/home.js"></script>
</body>

CRM Tele2 ASP/Views/OutGoingCall/OutGoingCallIndex.cshtml
@model ClientCallViewModel
@{
    var jsonOptions = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="stylesheet" href="~/css/OutGoingCall.css" asp-append-version="true" />
</head>

<body>
    <div class="container">
        <div class="stack-panel">
            <h1>История</h1>
            <div id="CallHistoryDiv">
                <table id="callHistoryTable">
                    <thead>
                        <tr>
                            <th>Комментарий</th>
                            <th>Дата последнего контакта</th>
                            <th>Отложено на</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
            <form asp-action="CreateCall" asp-controller="OutGoingCall" method="post">
                <div class="clientPhoneInputDiv">
                    <input type="text" asp-for="Call.ClientPhoneNumber" maxlength="12" id="phoneInput" class="form-control" autocomplete="off" placeholder="Номер телефона" value="+77" />
                    <span asp-validation-for="Call.ClientPhoneNumber" class="text-danger"></span>
                    <div id="suggestions" class="list-group"></div>
                </div>
                <div>
                    <input type="text" asp-for="Call.ClientName" maxlength="100" id="clientName" class="form-control" placeholder="Имя" />
                </div>
                <div>
                    <input type="text" asp-for="Call.ClientAddress" maxlength="100" id="clientAddress" class="form-control" placeholder="Адрес" />
                </div>
                <textarea placeholder="Комментарий" maxlength="500" asp-for="Call.Comment"></textarea>

                <label for="date-of-scheduled-call-input">Назначить звонок</label>
                <input id="date-of-scheduled-call-input" type="datetime-local" asp-for="Call.DateOfScheduledCall" />
                <button>Сохранить</button>
            </form>
        </div>
    </div>
    @if(Model != null)
    {
        <script>
            var clientFromServer = @Html.Raw(JsonSerializer.Serialize(Model.Client, jsonOptions));
            window.clientFromServer = clientFromServer;
        </script>
    }
    <script src="~/js/outgoing-call.js"></script>
</body>

CRM Tele2 ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRM_Tele2_ASP</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" rel="stylesheet" />
</head>
<body>
        <main>
            @RenderBody()
        </main>
    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery.validate.min.js"></script>
    <script src="~/lib/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

</body>

</html>